#%RAML 1.0 Library
usage: Collection of commonly reusable RAMLs

resourceTypes:
  createReadCollection: !include resourceTypes/collection/create-read.raml
  readUpdateDeleteItem: !include resourceTypes/item/read-update-delete.raml
  readItem: !include resourceTypes/item/read.raml
  updateItem: !include resourceTypes/item/update.raml
  deleteItem: !include resourceTypes/item/delete.raml

traits:
  #for caching
  hasCacheable: !include traits/caching/hasCacheable.raml

  #common traits
  hasCommonHeaders: !include traits/commons/hasCommonHeaders.raml

  #for pagination
  searchable: !include traits/pagination/hasCountable.raml
  sortable: !include traits/pagination/hasPageable.raml
  pageable: !include traits/pagination/hasSortable.raml

  #for rate-limiting
  hasRateLimiting: !include traits/rate-limiting/hasRateLimiting.raml