#%RAML 1.0 ResourceType
usage: Retrieve list of all records and/or create a single record

get:
  displayName: Get Resource Type for <<resourcePathName | !singularize | !uppercamelcase>> summary.
  description: Get Resource Type for <<resourcePathName | !singularize | !uppercamelcase>> summary.
  responses:
    200:
      description: Success Response
      body:
        application/json:
          example: <<getResponseExample>>
          type: <<getResponseType>>
    500:
      description: Success Response
      body:
        application/json:
          example: <<getResponseExample>>
          type: <<getResponseType>>
post:
  displayName: Post Resource Type for <<resourcePathName | !singularize | !uppercamelcase>> summary.
  description: Post Resource Type for <<resourcePathName | !singularize | !uppercamelcase>> summary.
  responses:
    201:
      description: Success Response
      body:
        application/json:
          example: <<postResponseExample>>