#%RAML 1.0 ResourceType
usage: Retrieve list of all records

get:
  displayName: Get Resource Type for <<resourcePathName | !singularize | !uppercamelcase>> summary.
  description: Get Resource Type for <<resourcePathName | !singularize | !uppercamelcase>> summary.
  responses:
    200:
      description: Success Response
      body:
        application/json:
          example: <<getResponseExample>>
          type: <<getResponseType>>