#%RAML 1.0 Trait
usage: Trait for GET methods that supports caching control

responses:
  200:
    headers: 
      Cache-Control:
        description: |
          Activates caching and defines cache behavior through cache response directives. 
          Usually defines public or private (cacheable by proxy or not) and max-age for resource.
        example: private, max-age=31536000