#%RAML 1.0 ResourceType
usage: Retrieve, update, or delete a single record

get:
  displayName: Get Resource Type for <<resourcePathName | !singularize | !uppercamelcase>>
  description: Get Resource Type for <<resourcePathName | !singularize | !uppercamelcase>>
  responses:
    200:
      description: |
        Success Response
      body:
        application/json:
          example: <<getResponseExample>>
          type: <<getResponseType>>
    500:
      description: |
        Internal Server Error
      body:
        application/json:
          example: <<errorResponseExample>>
          type: <<errorResponseType>>
    502:
      description: |
        Bad Gateway
      body:
        application/json:
          example: <<errorResponseExample>>
          type: <<errorResponseType>>
    504:
      description: |
        Gateway Timeout
      body:
        application/json:
          example: <<errorResponseExample>>
          type: <<errorResponseType>>
put:
  displayName: Put Resource Type for <<resourcePathName | !singularize | !uppercamelcase>>
  description: Put Resource Type for <<resourcePathName | !singularize | !uppercamelcase>>
  responses:
    200:
      description: |
        Success Response
      body:
        application/json:
          example: <<putResponseExample>>
    400:
      description: |
        Bad Request
      body:
        application/json:
          example: <<errorResponseExample>>
          type: <<errorResponseType>>
    500:
      description: |
        Internal Server Error
      body:
        application/json:
          example: <<errorResponseExample>>
          type: <<errorResponseType>>
    502:
      description: |
        Bad Gateway
      body:
        application/json:
          example: <<errorResponseExample>>
          type: <<errorResponseType>>
    504:
      description: |
        Gateway Timeout
      body:
        application/json:
          example: <<errorResponseExample>>
          type: <<errorResponseType>>
delete:
  displayName: Delete Resource Type for <<resourcePathName | !singularize | !uppercamelcase>> summary.
  description: Delete Resource Type for <<resourcePathName | !singularize | !uppercamelcase>> summary.
  responses:
    200:
      description: |
        Success Response
      body:
        application/json:
          example: <<deleteResponseExample>>
    500:
      description: |
        Internal Server Error
      body:
        application/json:
          example: <<errorResponseExample>>
          type: <<errorResponseType>>
    502:
      description: |
        Bad Gateway
      body:
        application/json:
          example: <<errorResponseExample>>
          type: <<errorResponseType>>
    504:
      description: |
        Gateway Timeout
      body:
        application/json:
          example: <<errorResponseExample>>
          type: <<errorResponseType>>