#%RAML 1.0 ResourceType
usage: Retrieve, update, or delete a single record

get:
  displayName: Get Resource Type for <<resourcePathName | !singularize | !uppercamelcase>> summary.
  description: Get Resource Type for <<resourcePathName | !singularize | !uppercamelcase>> summary.
  responses:
    200:
      description: Success Response
      body:
        application/json:
          example: <<getResponseExample>>
          type: <<getResponseType>>
put:
  displayName: Put Resource Type for <<resourcePathName | !singularize | !uppercamelcase>> summary.
  description: Put Resource Type for <<resourcePathName | !singularize | !uppercamelcase>> summary.
  responses:
    200:
      description: Success Response
      body:
        application/json:
          example: <<patchResponseExample>>
delete:
  displayName: Delete Resource Type for <<resourcePathName | !singularize | !uppercamelcase>> summary.
  description: Delete Resource Type for <<resourcePathName | !singularize | !uppercamelcase>> summary.
  responses:
    200:
      description: Success Response
      body:
        application/json:
          example: <<deleteResponseExample>>