#%RAML 1.0 ResourceType
usage: Create and save a single record

post:
  displayName: Post Resource Type for <<resourcePathName | !singularize | !uppercamelcase>> summary.
  description: Post Resource Type for <<resourcePathName | !singularize | !uppercamelcase>> summary.
  responses:
    200:
      description: Success Response
      body:
        application/json:
          example: <<recordType>> successfully created!