#%RAML 1.0 ResourceType
usage: Update a single record

put:
  displayName: Put Resource Type for <<resourcePathName | !singularize | !uppercamelcase>> summary.
  description: Patch Resource Type for <<resourcePathName | !singularize | !uppercamelcase>> summary.
  responses:
    200:
      description: Success Response
      body:
        application/json:
          example: <<patchResponseExample>>
          type: <<patchResponseType>>